# Generated by Django 4.0.5 on 2022-07-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('dateCurrent', models.DateTimeField(auto_now_add=True)),
                ('date', models.IntegerField()),
                ('time', models.IntegerField()),
                ('people', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
