# Generated by Django 4.0.6 on 2022-07-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menu_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_cost',
            field=models.FloatField(),
        ),
    ]
