# Generated by Django 4.0.6 on 2022-07-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_menu_menu_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('dinner', 'Dinner'), ('starters', 'Starters'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch')], max_length=20, null=True),
        ),
    ]
