# Generated by Django 4.0.6 on 2022-07-15 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_menu_menu_type_menureservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('starters', 'Starters'), ('breakfast', 'Breakfast'), ('dinner', 'Dinner'), ('lunch', 'Lunch')], max_length=20, null=True),
        ),
    ]
