# Generated by Django 4.0.6 on 2022-07-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_review_body_review_writer_alter_menu_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('lunch', 'Lunch'), ('breakfast', 'Breakfast'), ('starters', 'Starters'), ('dinner', 'Dinner')], max_length=20, null=True),
        ),
    ]
